version: '3.9'

services:

  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../mesto-frontend/dist/:/var/html/
      - ../static:/var/html/static/
      - ../media/:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"